### ISSUE TITLE
Firmware Versioning

### ISSUE THREAD

**Issue by jlingema** [jlingema/cmssw#3]
Need a mechanism to take firmware version into account. Either implement factory or make simple ifs where anticipated?

see Calo Producer:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/L1Trigger/L1TCalorimeter/plugins/L1TStage1Layer2Producer.cc#L388

**Comment by jlingema** [comment]
I think we need a bit of a discussion with @dinyar what changes to expect we are expecting in the algorithm.

**Comment by thomreis** [comment]
As mentioned in https://github.com/jlingema/cmssw/issues/4 factories for the LUTs were implemented.
Input and output widths for the LUTs will be hardcoded in the FW version dependent LUT implementation in the future.

**Comment by thomreis** [comment]
The LUT factories are included in PR
https://github.com/cms-l1t-offline/cmssw/pull/59

**Comment by thomreis** [comment]
Merged in l1t-muon-CMSSW_7_6_0_pre5 branch in cms-l1t-offline.
