### ISSUE TITLE
Move LUT to CondFormat

### ISSUE THREAD

**Issue by jlingema** [jlingema/cmssw#5]
LUTs shuld be configurable from DB and also versionable. This needs some re-writing of the corresponding classes. Probably just need to touch MicroGMTLut.h...

Calo LUT object:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/CondFormats/L1TObjects/interface/LUT.h

**Comment by thomreis** [comment]
https://github.com/cms-l1t-offline/cmssw/pull/59

**Comment by thomreis** [comment]
Merged this in l1t-muon-CMSSW_7_6_0_pre5
